//! Typed ID newtypes, backed by UUID v7 for lexicographic ordering.

use uuid::Uuid;

/// Generate a new UUID v7 value.
#[must_use]
pub fn new_id() -> Uuid {
    Uuid::now_v7()
}

/// Macro to define a typed newtype ID. Each domain crate uses this to
/// create strongly-typed identifiers that do not silently interchange.
///
/// The doc comments below are emitted into each invocation's
/// generated struct + `new()` so `#![warn(missing_docs)]` (set on
/// every crate) doesn't fire per-id; without these the generated
/// items inherit the macro-call site and clippy can't see prose.
#[macro_export]
macro_rules! define_id {
    ($name:ident) => {
        #[doc = concat!(
            "Typed UUID-v7 identifier. Generated by `define_id!(",
            stringify!($name),
            ")`; see `kubinate_platform::ids` for the macro's contract."
        )]
        #[derive(
            Debug,
            Clone,
            Copy,
            PartialEq,
            Eq,
            Hash,
            ::serde::Serialize,
            ::serde::Deserialize,
            ::sqlx::Type,
        )]
        #[sqlx(transparent)]
        pub struct $name(pub ::uuid::Uuid);

        impl $name {
            #[doc = concat!(
                "Mint a fresh ",
                stringify!($name),
                " backed by `uuid::Uuid::now_v7`."
            )]
            #[must_use]
            pub fn new() -> Self {
                Self(::uuid::Uuid::now_v7())
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                self.0.fmt(f)
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }
    };
}

// Example baseline ID types used across crates.
define_id!(UserId);
define_id!(OrganizationId);
