//! Envelope encryption primitives.
//!
//! In Phases 0–2 this module wraps pgcrypto under a narrow API. In
//! Phase 3, the same API switches to talk to Vault's transit engine
//! (see ADR-0007). Call sites do not need to change.
//!
//! # Guarantees
//!
//! - Plaintext exists in Rust memory only inside a single method call,
//!   and only wrapped in a [`SecretString`] whose `Debug` impl redacts
//!   the contents.
//! - The KEK is loaded once at startup from `KUBINATE__KEK` and is held
//!   in a [`SecretString`] for the lifetime of the [`PgcryptoStore`];
//!   it is never serialized or logged.
//! - Every insert/read/delete opens a tenant-scoped transaction that
//!   issues `SET LOCAL app.current_tenant_id`, so RLS on the `secrets`
//!   table enforces cross-tenant isolation even if a caller passes in
//!   the wrong organization.

use async_trait::async_trait;
use base64::{engine::general_purpose::STANDARD as B64, Engine};
use secrecy::{ExposeSecret, SecretString};
use sqlx::PgPool;
use thiserror::Error;
use uuid::Uuid;

use crate::metrics::names::SECRET_STORE_DISPATCH_TOTAL;

/// A handle to a secret whose ciphertext lives in the database.
///
/// The handle is cheap to `Clone` / `Copy` and safe to log — it carries
/// only identifiers, never key material. The `organization_id` is part
/// of the handle so that the store can scope the lookup transaction
/// correctly without requiring a separate parameter on every call.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SecretRef {
    /// Primary key of the `secrets` row.
    pub id: Uuid,
    /// Owning tenant. Must match the `app.current_tenant_id` of any
    /// transaction that reads the row, or RLS will reject the lookup.
    pub organization_id: Uuid,
}

/// Errors raised by the secrets subsystem.
#[derive(Debug, Error)]
pub enum SecretError {
    /// The secret could not be found (or was hidden by RLS).
    #[error("secret not found: {0}")]
    NotFound(Uuid),
    /// Decryption failed — usually a KEK mismatch or tampered ciphertext.
    #[error("decryption failed")]
    Decrypt,
    /// The configured KEK / `AppRole` token failed validation at
    /// construction time. Operator action: check the env var.
    #[error("invalid KEK: {0}")]
    InvalidKek(String),
    /// The remote secret backend rejected our credential. Distinct
    /// from [`Self::InvalidKek`] so on-call can tell "rotate the
    /// `AppRole` secret-id" (this) apart from "fix the env var"
    /// (`InvalidKek`). Vault 401 (token expired/revoked), 403 (policy
    /// denial), and 404 on encrypt/decrypt (key not found) all map
    /// here. The string is the HTTP status only — bodies are
    /// scrubbed before they reach this variant to keep tracing logs
    /// from echoing key paths or error fragments.
    #[error("backend auth failed: {0}")]
    AuthFailed(String),
    /// Underlying database failure.
    #[error(transparent)]
    Database(#[from] sqlx::Error),
}

/// Abstract secret store. Implementations: [`PgcryptoStore`] (phases 0–2),
/// `VaultStore` (phase 3+ — see ADR-0007).
#[async_trait]
pub trait SecretStore: Send + Sync {
    /// Encrypt a plaintext and return a handle scoped to `organization_id`.
    async fn put(
        &self,
        organization_id: Uuid,
        plaintext: SecretString,
    ) -> Result<SecretRef, SecretError>;

    /// Resolve a handle back to plaintext.
    ///
    /// Callers must drop the returned [`SecretString`] as soon as the
    /// plaintext is no longer needed. The `integrations::hetzner`
    /// client, for example, resolves and forgets the token within a
    /// single HTTP call (ADR-0007, threat-model Flow 2).
    async fn get(&self, handle: &SecretRef) -> Result<SecretString, SecretError>;

    /// Zero the ciphertext in place and delete the row.
    async fn delete(&self, handle: &SecretRef) -> Result<(), SecretError>;
}

/// pgcrypto-backed [`SecretStore`].
///
/// Uses two layers of `pgp_sym_encrypt` to realise envelope encryption:
/// a per-row DEK is generated by `gen_random_bytes` inside a single
/// SQL statement, encrypts the plaintext, and is itself encrypted under
/// the application-wide KEK before being stored alongside the ciphertext.
pub struct PgcryptoStore {
    pool: PgPool,
    kek: SecretString,
}

impl PgcryptoStore {
    /// Build a store with an explicit base64-encoded 32-byte KEK.
    ///
    /// # Errors
    /// Returns [`SecretError::InvalidKek`] if the KEK is not valid
    /// base64 or does not decode to exactly 32 bytes.
    pub fn new(pool: PgPool, kek: SecretString) -> Result<Self, SecretError> {
        let decoded = B64
            .decode(kek.expose_secret().as_bytes())
            .map_err(|e| SecretError::InvalidKek(format!("not valid base64: {e}")))?;
        if decoded.len() != 32 {
            return Err(SecretError::InvalidKek(format!(
                "expected 32 bytes, got {}",
                decoded.len()
            )));
        }
        Ok(Self { pool, kek })
    }

    /// Build a store using the KEK loaded from `KUBINATE__KEK`.
    ///
    /// # Errors
    /// Returns [`SecretError::InvalidKek`] if the env var is unset or
    /// fails the validation rules documented on [`Self::new`].
    pub fn from_env(pool: PgPool) -> Result<Self, SecretError> {
        let kek = std::env::var("KUBINATE__KEK")
            .map_err(|_| SecretError::InvalidKek("KUBINATE__KEK not set".to_string()))?;
        Self::new(pool, SecretString::from(kek))
    }
}

#[async_trait]
impl SecretStore for PgcryptoStore {
    async fn put(
        &self,
        organization_id: Uuid,
        plaintext: SecretString,
    ) -> Result<SecretRef, SecretError> {
        metrics::counter!(SECRET_STORE_DISPATCH_TOTAL, "backend" => "pgcrypto", "op" => "put")
            .increment(1);
        let id = Uuid::now_v7();

        let mut tx = self.pool.begin().await?;
        sqlx::query(&set_local_tenant(organization_id))
            .execute(&mut *tx)
            .await?;

        // `WITH ... AS MATERIALIZED` forces the DEK to be generated once
        // and reused on both sides of the envelope. Without MATERIALIZED
        // the planner is free to inline the CTE and evaluate it twice.
        sqlx::query(
            r"
            WITH dek_raw AS MATERIALIZED (
                SELECT gen_random_bytes(32) AS raw
            )
            INSERT INTO secrets (id, organization_id, ciphertext, wrapped_dek)
            SELECT
                $1,
                $2,
                pgp_sym_encrypt($3, encode(dek.raw, 'base64')),
                pgp_sym_encrypt(encode(dek.raw, 'base64'), $4)
            FROM dek_raw dek
            ",
        )
        .bind(id)
        .bind(organization_id)
        .bind(plaintext.expose_secret())
        .bind(self.kek.expose_secret())
        .execute(&mut *tx)
        .await?;

        tx.commit().await?;

        tracing::debug!(secret_id = %id, org = %organization_id, "secret stored");
        Ok(SecretRef {
            id,
            organization_id,
        })
    }

    async fn get(&self, handle: &SecretRef) -> Result<SecretString, SecretError> {
        metrics::counter!(SECRET_STORE_DISPATCH_TOTAL, "backend" => "pgcrypto", "op" => "get")
            .increment(1);
        let mut tx = self.pool.begin().await?;
        sqlx::query(&set_local_tenant(handle.organization_id))
            .execute(&mut *tx)
            .await?;

        let row: Option<(String,)> = sqlx::query_as(
            r"
            SELECT pgp_sym_decrypt(
                       ciphertext,
                       pgp_sym_decrypt(wrapped_dek, $2)
                   )
            FROM secrets
            WHERE id = $1
            ",
        )
        .bind(handle.id)
        .bind(self.kek.expose_secret())
        .fetch_optional(&mut *tx)
        .await
        .map_err(decrypt_or_db)?;

        tx.commit().await?;

        match row {
            Some((plaintext,)) => Ok(SecretString::from(plaintext)),
            None => Err(SecretError::NotFound(handle.id)),
        }
    }

    async fn delete(&self, handle: &SecretRef) -> Result<(), SecretError> {
        metrics::counter!(SECRET_STORE_DISPATCH_TOTAL, "backend" => "pgcrypto", "op" => "delete")
            .increment(1);
        let mut tx = self.pool.begin().await?;
        sqlx::query(&set_local_tenant(handle.organization_id))
            .execute(&mut *tx)
            .await?;

        // Overwrite ciphertext + wrapped DEK before the delete. Postgres
        // MVCC leaves dead tuples on disk until VACUUM, so this is not
        // cryptographic erasure — true crypto-shredding is a Vault/KMS
        // property we pick up in Phase 3. This is still defence-in-depth:
        // anything reading the current row version sees no key material.
        sqlx::query(
            "UPDATE secrets SET ciphertext = ''::bytea, wrapped_dek = ''::bytea WHERE id = $1",
        )
        .bind(handle.id)
        .execute(&mut *tx)
        .await?;

        sqlx::query("DELETE FROM secrets WHERE id = $1")
            .bind(handle.id)
            .execute(&mut *tx)
            .await?;

        tx.commit().await?;
        Ok(())
    }
}

/// Build a `SET LOCAL` statement for the tenant discriminator.
///
/// Postgres's `SET` command does not accept bind parameters, so the
/// UUID has to be interpolated. [`Uuid::Display`] emits hex + dashes
/// only, which cannot produce SQL injection.
fn set_local_tenant(organization_id: Uuid) -> String {
    format!("SET LOCAL app.current_tenant_id = '{organization_id}'")
}

fn decrypt_or_db(err: sqlx::Error) -> SecretError {
    // pgcrypto surfaces bad KEK / tampered ciphertext as a database
    // error with a recognisable message. Everything else is bubbled up
    // as-is so that the surrounding context can handle it.
    let text = err.to_string().to_ascii_lowercase();
    if text.contains("wrong key") || text.contains("corrupt data") {
        SecretError::Decrypt
    } else {
        SecretError::Database(err)
    }
}

// ===========================================================================
// Sprint 4 ticket 02 — Vault transit-engine SecretStore.
//
// The `VaultStore` is a drop-in replacement for `PgcryptoStore` behind
// the `SecretStore` trait. The pgcrypto path stays compiled in; the
// API binary picks one at startup via the `KUBINATE__SECRETS_BACKEND`
// env var. Migration tooling that re-keys existing rows is out of
// scope for this chunk — see `docs/backlog/sprint-4/02-vault-migration.md`
// "Sprint 4 partial scope" for the full path.
//
// Design:
//
// - The `secrets` table layout is unchanged. Vault rows write
//   `algorithm = 'vault_transit_v1'`; pgcrypto rows continue to
//   write the default `'pgp_sym_v1'`. The `algorithm` column is the
//   discriminator a future migration binary reads to know which
//   backend originally encrypted a row.
// - The `wrapped_dek` column is empty for Vault rows — Vault's
//   transit engine manages the DEK lifecycle internally; we never
//   see one. The column stays NOT NULL by storing an empty BYTEA
//   so the schema can carry both backends without a migration.
// - The HTTP client to a real Vault is **not** in this chunk. The
//   `VaultTransit` trait is the seam; an `HttpVaultTransit` impl
//   lands once a real Vault deploy exists for it to hit (Sprint
//   5+). The `InMemoryVaultTransit` test impl exercises the full
//   `SecretStore` contract against `VaultStore` so the trait-level
//   parity property is verified in CI today.
// ===========================================================================

/// Algorithm tag for Vault-encrypted rows in the `secrets` table.
/// Pinned as a constant so a typo in either the writer or the
/// reader fails loudly rather than silently writing rows the other
/// backend can't decrypt.
pub const VAULT_ALGORITHM_TAG: &str = "vault_transit_v1";

/// Per-org Vault key naming. `kubinate/<organization_id>` keeps
/// transit keys isolated per tenant; a leaked key compromises one
/// org, not the fleet. The `kubinate/` prefix matches the
/// `KUBINATE__VAULT_KEY_PREFIX` env var the future
/// `HttpVaultTransit` reads (default `kubinate`).
fn vault_key_name(prefix: &str, organization_id: Uuid) -> String {
    format!("{prefix}/{organization_id}")
}

/// Abstraction over the Vault transit engine. Production uses a
/// reqwest-backed HTTP impl (Sprint 5+); tests use
/// [`InMemoryVaultTransit`].
///
/// Operations map 1:1 with Vault transit endpoints:
/// - [`Self::ensure_key`] — `POST /v1/transit/keys/<name>` (idempotent).
/// - [`Self::encrypt`] — `POST /v1/transit/encrypt/<name>`.
/// - [`Self::decrypt`] — `POST /v1/transit/decrypt/<name>`.
#[async_trait]
pub trait VaultTransit: Send + Sync {
    /// Ensure the named transit key exists. Vault returns 204 on
    /// create and 204 on a no-op re-create; both are success.
    async fn ensure_key(&self, key_name: &str) -> Result<(), SecretError>;

    /// Encrypt plaintext under the named key. Returns the
    /// `vault:vN:...` envelope string Vault hands back.
    async fn encrypt(&self, key_name: &str, plaintext: &str) -> Result<String, SecretError>;

    /// Decrypt a `vault:vN:...` envelope back to plaintext.
    async fn decrypt(&self, key_name: &str, ciphertext: &str) -> Result<String, SecretError>;
}

/// In-memory [`VaultTransit`] for tests. Keys + plaintext live in a
/// `Mutex<HashMap>`; ciphertext is a deterministic synthetic string
/// `vault:test:<uuid>` whose suffix indexes back into the map. No
/// real cryptography — the production HTTP impl carries that.
///
/// Why deterministic ciphertext: the parity tests (see
/// `crates/platform/tests/secrets.rs`) need to assert that a
/// re-read of a `secrets` row produces the same plaintext, which
/// requires that the ciphertext written under a particular `put`
/// resolves stably under a later `get`. A random-per-encrypt
/// fake would still satisfy the contract via the `HashMap`, but
/// debugging a failing parity test is easier when the ciphertext
/// looks like the row id.
pub struct InMemoryVaultTransit {
    inner: std::sync::Mutex<InMemoryVault>,
}

#[derive(Default)]
struct InMemoryVault {
    /// `key_name -> exists`.
    keys: std::collections::HashSet<String>,
    /// `(key_name, ciphertext) -> plaintext`.
    ciphertexts: std::collections::HashMap<(String, String), String>,
    /// Monotonic counter for synthetic ciphertext ids.
    counter: u64,
}

impl InMemoryVaultTransit {
    /// Build an empty in-memory transit fake.
    #[must_use]
    pub fn new() -> Self {
        Self {
            inner: std::sync::Mutex::new(InMemoryVault::default()),
        }
    }
}

impl Default for InMemoryVaultTransit {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl VaultTransit for InMemoryVaultTransit {
    async fn ensure_key(&self, key_name: &str) -> Result<(), SecretError> {
        let mut g = self.inner.lock().expect("vault transit fake poisoned");
        g.keys.insert(key_name.to_string());
        Ok(())
    }

    async fn encrypt(&self, key_name: &str, plaintext: &str) -> Result<String, SecretError> {
        let mut g = self.inner.lock().expect("vault transit fake poisoned");
        if !g.keys.contains(key_name) {
            return Err(SecretError::InvalidKek(format!(
                "no transit key named '{key_name}'"
            )));
        }
        g.counter += 1;
        let ciphertext = format!("vault:test:{:016x}", g.counter);
        g.ciphertexts.insert(
            (key_name.to_string(), ciphertext.clone()),
            plaintext.to_string(),
        );
        Ok(ciphertext)
    }

    async fn decrypt(&self, key_name: &str, ciphertext: &str) -> Result<String, SecretError> {
        let g = self.inner.lock().expect("vault transit fake poisoned");
        if !g.keys.contains(key_name) {
            return Err(SecretError::InvalidKek(format!(
                "no transit key named '{key_name}'"
            )));
        }
        g.ciphertexts
            .get(&(key_name.to_string(), ciphertext.to_string()))
            .cloned()
            .ok_or(SecretError::Decrypt)
    }
}

/// Vault-transit-backed [`SecretStore`].
///
/// The shape is:
///
/// 1. `put` — generate a synthetic per-org Vault key name, ensure
///    it exists in Vault, encrypt the plaintext, persist the
///    ciphertext + algorithm tag in the `secrets` table.
/// 2. `get` — load the row, send the ciphertext back to Vault
///    decrypt, return the plaintext.
/// 3. `delete` — same blank-and-DELETE shape as `PgcryptoStore`.
///
/// The `key_prefix` segment of the Vault key name is configurable
/// so different deploys (staging / production) can share a Vault
/// instance without colliding.
pub struct VaultStore<T: VaultTransit> {
    pool: PgPool,
    transit: T,
    key_prefix: String,
}

impl<T: VaultTransit> VaultStore<T> {
    /// Build a [`VaultStore`] from a pool, a transit client, and
    /// the per-deploy key-name prefix. The prefix is intended to
    /// be loaded from `KUBINATE__VAULT_KEY_PREFIX` (default
    /// `kubinate`) — wiring lives at the API edge, not here.
    #[must_use]
    pub fn new(pool: PgPool, transit: T, key_prefix: impl Into<String>) -> Self {
        Self {
            pool,
            transit,
            key_prefix: key_prefix.into(),
        }
    }
}

#[async_trait]
impl<T: VaultTransit> SecretStore for VaultStore<T> {
    async fn put(
        &self,
        organization_id: Uuid,
        plaintext: SecretString,
    ) -> Result<SecretRef, SecretError> {
        metrics::counter!(SECRET_STORE_DISPATCH_TOTAL, "backend" => "vault", "op" => "put")
            .increment(1);
        let key_name = vault_key_name(&self.key_prefix, organization_id);

        // Lazy key creation — idempotent on the Vault side. We
        // could move this out to a startup-time "ensure all org
        // keys exist" pass, but that doesn't compose with the
        // multi-tenant lifecycle (orgs come and go); per-`put`
        // ensure_key is the simplest correct shape.
        self.transit.ensure_key(&key_name).await?;
        let ciphertext_str = self
            .transit
            .encrypt(&key_name, plaintext.expose_secret())
            .await?;

        let id = Uuid::now_v7();
        let mut tx = self.pool.begin().await?;
        sqlx::query(&set_local_tenant(organization_id))
            .execute(&mut *tx)
            .await?;
        sqlx::query(
            r"
            INSERT INTO secrets (id, organization_id, ciphertext, wrapped_dek, algorithm)
            VALUES ($1, $2, $3, $4, $5)
            ",
        )
        .bind(id)
        .bind(organization_id)
        .bind(ciphertext_str.as_bytes())
        // Vault-managed keys: no per-row DEK to wrap. The column is
        // NOT NULL so we store an empty BYTEA; readers must consult
        // `algorithm` before treating `wrapped_dek` as meaningful.
        .bind::<&[u8]>(b"")
        .bind(VAULT_ALGORITHM_TAG)
        .execute(&mut *tx)
        .await?;

        tx.commit().await?;
        tracing::debug!(
            secret_id = %id,
            org = %organization_id,
            backend = "vault",
            "secret stored"
        );
        Ok(SecretRef {
            id,
            organization_id,
        })
    }

    async fn get(&self, handle: &SecretRef) -> Result<SecretString, SecretError> {
        metrics::counter!(SECRET_STORE_DISPATCH_TOTAL, "backend" => "vault", "op" => "get")
            .increment(1);
        let mut tx = self.pool.begin().await?;
        sqlx::query(&set_local_tenant(handle.organization_id))
            .execute(&mut *tx)
            .await?;

        let row: Option<(Vec<u8>, String)> =
            sqlx::query_as("SELECT ciphertext, algorithm FROM secrets WHERE id = $1")
                .bind(handle.id)
                .fetch_optional(&mut *tx)
                .await?;
        tx.commit().await?;

        let Some((ciphertext_bytes, algorithm)) = row else {
            return Err(SecretError::NotFound(handle.id));
        };
        if algorithm != VAULT_ALGORITHM_TAG {
            // Wrong-backend read: a row written by `PgcryptoStore`
            // cannot be decrypted here without re-encryption. Map
            // to Decrypt so the caller surfaces the same shape it
            // would for a tampered ciphertext.
            return Err(SecretError::Decrypt);
        }
        let ciphertext_str =
            std::str::from_utf8(&ciphertext_bytes).map_err(|_| SecretError::Decrypt)?;

        let key_name = vault_key_name(&self.key_prefix, handle.organization_id);
        let plaintext = self.transit.decrypt(&key_name, ciphertext_str).await?;
        Ok(SecretString::from(plaintext))
    }

    async fn delete(&self, handle: &SecretRef) -> Result<(), SecretError> {
        metrics::counter!(SECRET_STORE_DISPATCH_TOTAL, "backend" => "vault", "op" => "delete")
            .increment(1);
        let mut tx = self.pool.begin().await?;
        sqlx::query(&set_local_tenant(handle.organization_id))
            .execute(&mut *tx)
            .await?;
        sqlx::query(
            "UPDATE secrets SET ciphertext = ''::bytea, wrapped_dek = ''::bytea WHERE id = $1",
        )
        .bind(handle.id)
        .execute(&mut *tx)
        .await?;
        sqlx::query("DELETE FROM secrets WHERE id = $1")
            .bind(handle.id)
            .execute(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(())
    }
}

/// Production [`VaultTransit`] talking to a real `HashiCorp` Vault
/// instance via its HTTP API.
///
/// Three endpoints, all under `/v1/transit/`:
/// - `POST keys/<name>` — create the named key (idempotent on
///   the Vault side; we treat 200 + 204 as success and any 4xx
///   that mentions "exists" as benign).
/// - `POST encrypt/<name>` — body `{"plaintext": "<base64>"}`
///   → response `{"data": {"ciphertext": "vault:vN:..."}}`.
/// - `POST decrypt/<name>` — body `{"ciphertext": "vault:vN:..."}`
///   → response `{"data": {"plaintext": "<base64>"}}`.
///
/// The token is held in a [`SecretString`] for the lifetime of the
/// client; rotation is operator-triggered (an upstream Vault flow
/// re-issues + we restart). Sprint 5+ ticket: rotate without
/// restart by hot-swapping the token via a periodic
/// `tokio::sync::Notify`.
pub struct HttpVaultTransit {
    client: reqwest::Client,
    base_url: url::Url,
    token: SecretString,
}

impl HttpVaultTransit {
    /// Build with an explicit Vault base URL + token. The base URL
    /// must include the scheme (`https://vault.example.com`); the
    /// `/v1/transit/` segments are appended internally.
    ///
    /// # Errors
    /// [`SecretError::InvalidKek`] when the URL doesn't parse or
    /// the reqwest client cannot be built.
    pub fn new(base_url: &str, token: SecretString) -> Result<Self, SecretError> {
        let parsed = url::Url::parse(base_url).map_err(|e| {
            SecretError::InvalidKek(format!("KUBINATE__VAULT_ADDR invalid url: {e}"))
        })?;
        let client = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(15))
            .build()
            .map_err(|e| SecretError::InvalidKek(format!("reqwest client: {e}")))?;
        Ok(Self {
            client,
            base_url: parsed,
            token,
        })
    }

    /// Build from `KUBINATE__VAULT_ADDR` + `KUBINATE__VAULT_TOKEN`.
    /// Both env vars are required.
    ///
    /// # Errors
    /// [`SecretError::InvalidKek`] when either var is missing or
    /// malformed.
    pub fn from_env() -> Result<Self, SecretError> {
        let addr = std::env::var("KUBINATE__VAULT_ADDR")
            .map_err(|_| SecretError::InvalidKek("KUBINATE__VAULT_ADDR not set".into()))?;
        let token = std::env::var("KUBINATE__VAULT_TOKEN")
            .map_err(|_| SecretError::InvalidKek("KUBINATE__VAULT_TOKEN not set".into()))?;
        Self::new(&addr, SecretString::from(token))
    }

    fn url_for(&self, segment: &str) -> Result<url::Url, SecretError> {
        let path = format!("v1/transit/{segment}");
        self.base_url
            .join(&path)
            .map_err(|e| SecretError::InvalidKek(format!("vault url join: {e}")))
    }
}

#[derive(serde::Serialize)]
struct VaultEncryptRequest<'a> {
    plaintext: &'a str,
}

#[derive(serde::Deserialize)]
struct VaultEncryptResponse {
    data: VaultEncryptData,
}

#[derive(serde::Deserialize)]
struct VaultEncryptData {
    ciphertext: String,
}

#[derive(serde::Serialize)]
struct VaultDecryptRequest<'a> {
    ciphertext: &'a str,
}

#[derive(serde::Deserialize)]
struct VaultDecryptResponse {
    data: VaultDecryptData,
}

#[derive(serde::Deserialize)]
struct VaultDecryptData {
    plaintext: String,
}

/// Map a Vault HTTP status (without the body — bodies are scrubbed
/// before they reach error variants to keep tracing logs from
/// echoing key paths or response fragments) to a `SecretError`.
///
/// - 401 / 403 → `AuthFailed` (rotate the `AppRole` secret-id; check
///   the policy).
/// - 404 → `AuthFailed` ("key not found" — usually means the
///   `AppRole`'s policy doesn't grant create on the key path, or the
///   key was deleted out-of-band).
/// - 400 with the upstream "could not be decrypted" sentinel →
///   `Decrypt` (handled by the caller, which already has the body
///   for that one specific match).
/// - everything else (5xx, transport) → `InvalidKek` ("operational
///   misconfiguration; not auth, not tampered ciphertext").
fn vault_status_to_error(status: reqwest::StatusCode, op: &str) -> SecretError {
    match status.as_u16() {
        401 | 403 | 404 => SecretError::AuthFailed(format!("vault {op} {status}")),
        _ => SecretError::InvalidKek(format!("vault {op} {status}")),
    }
}

#[async_trait]
impl VaultTransit for HttpVaultTransit {
    async fn ensure_key(&self, key_name: &str) -> Result<(), SecretError> {
        let url = self.url_for(&format!("keys/{key_name}"))?;
        let response = self
            .client
            .post(url)
            .header("X-Vault-Token", self.token.expose_secret())
            // Body is required by Vault's transit/keys endpoint;
            // empty JSON is enough since the defaults
            // (`type = "aes256-gcm96"`) suit our use.
            .header("Content-Type", "application/json")
            .body("{}")
            .send()
            .await
            .map_err(|e| {
                tracing::debug!(error = %e, op = "ensure_key", "vault transport");
                SecretError::InvalidKek("vault ensure_key transport".into())
            })?;
        let status = response.status();
        // Vault returns 204 on create + 204 on no-op re-create; both success.
        if status.is_success() {
            return Ok(());
        }
        // Read the body for the "already exists" sentinel (benign)
        // and to log at debug level. Body never reaches the error
        // variant — tracing logs an Vault-error error variant
        // never echoes back a key path or echoed token name.
        let body = response.text().await.unwrap_or_default();
        if body.to_lowercase().contains("already exists") {
            return Ok(());
        }
        tracing::debug!(op = "ensure_key", %status, body, "vault non-success");
        Err(vault_status_to_error(status, "ensure_key"))
    }

    async fn encrypt(&self, key_name: &str, plaintext: &str) -> Result<String, SecretError> {
        use base64::{engine::general_purpose::STANDARD as B64, Engine};
        let url = self.url_for(&format!("encrypt/{key_name}"))?;
        let body = VaultEncryptRequest {
            plaintext: &B64.encode(plaintext.as_bytes()),
        };
        let response = self
            .client
            .post(url)
            .header("X-Vault-Token", self.token.expose_secret())
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                tracing::debug!(error = %e, op = "encrypt", "vault transport");
                SecretError::InvalidKek("vault encrypt transport".into())
            })?;
        let status = response.status();
        if !status.is_success() {
            let body = response.text().await.unwrap_or_default();
            tracing::debug!(op = "encrypt", %status, body, "vault non-success");
            return Err(vault_status_to_error(status, "encrypt"));
        }
        let parsed: VaultEncryptResponse = response.json().await.map_err(|e| {
            tracing::debug!(error = %e, op = "encrypt", "vault json parse");
            SecretError::InvalidKek("vault encrypt response parse".into())
        })?;
        Ok(parsed.data.ciphertext)
    }

    async fn decrypt(&self, key_name: &str, ciphertext: &str) -> Result<String, SecretError> {
        use base64::{engine::general_purpose::STANDARD as B64, Engine};
        let url = self.url_for(&format!("decrypt/{key_name}"))?;
        let body = VaultDecryptRequest { ciphertext };
        let response = self
            .client
            .post(url)
            .header("X-Vault-Token", self.token.expose_secret())
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                tracing::debug!(error = %e, op = "decrypt", "vault transport");
                SecretError::InvalidKek("vault decrypt transport".into())
            })?;
        let status = response.status();
        if !status.is_success() {
            let body = response.text().await.unwrap_or_default();
            tracing::debug!(op = "decrypt", %status, body, "vault non-success");
            // Vault returns 400 with body containing "ciphertext
            // could not be decrypted" for tampered ciphertext.
            // Match that specific case before the generic mapping.
            if body.to_lowercase().contains("could not be decrypted") {
                return Err(SecretError::Decrypt);
            }
            return Err(vault_status_to_error(status, "decrypt"));
        }
        let parsed: VaultDecryptResponse =
            response.json().await.map_err(|_| SecretError::Decrypt)?;
        let plaintext_bytes = B64
            .decode(parsed.data.plaintext.as_bytes())
            .map_err(|_| SecretError::Decrypt)?;
        String::from_utf8(plaintext_bytes).map_err(|_| SecretError::Decrypt)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn secret_string_debug_is_redacted() {
        let secret = SecretString::from("hcloud_supersecret_token_value".to_string());
        let rendered = format!("{secret:?}");
        assert!(
            rendered.contains("REDACTED"),
            "SecretString Debug must render as REDACTED, got: {rendered}",
        );
        assert!(
            !rendered.contains("hcloud_supersecret_token_value"),
            "SecretString Debug leaked the plaintext: {rendered}",
        );
    }

    #[test]
    fn new_rejects_kek_that_is_not_base64() {
        // We can't easily construct a PgcryptoStore without a pool, but
        // we can exercise the KEK-decoding branch via the base64 crate
        // directly to guarantee the error shape stays stable.
        let bad = SecretString::from("not!!!valid!!!base64".to_string());
        let err = B64.decode(bad.expose_secret().as_bytes()).unwrap_err();
        assert!(format!("{err}").to_lowercase().contains("invalid"));
    }
}
